image: decentraland/ci-node:latest

build:
  variables:
    NODE_OPTIONS: --max-old-space-size=8192
  only:
    - master
    - staging
    - release
  script:
    - ./setupEnv.sh
    - npm install && npm run build
    - dcl-lock-sync
    - cd .ci && npm install && dcl-up website-account
    - dcl-sync-release && cd ..
    - dcl-upload build
    - cd .ci && dcl-cache-invalidation
