name: CI

on: [push]

jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      # Enable when a test is added
      # - name: Test
      #   run: npm test -- --coverage
      #   if: ${{ always() }}
